In [1]:
import requests

In [5]:
lat=23.033863
lon=72.585022
key="f29183d2458d620a96494ac639fea754"
url=f"https://api.openweathermap.org/data/2.5/weather?lat={lat}&lon={lon}&appid={key}"
data=requests.get(url)
data.status_code

200

In [21]:
import json
final=data.json()
new=json.dumps(final,indent=5)
print(new)

{
     "coord": {
          "lon": 72.5873,
          "lat": 23.0258
     },
     "weather": [
          {
               "id": 801,
               "main": "Clouds",
               "description": "few clouds",
               "icon": "02d"
          }
     ],
     "base": "stations",
     "main": {
          "temp": 312.16,
          "feels_like": 314.02,
          "temp_min": 312.16,
          "temp_max": 312.16,
          "pressure": 1004,
          "humidity": 29,
          "sea_level": 1004,
          "grnd_level": 999
     },
     "visibility": 6000,
     "wind": {
          "speed": 4.63,
          "deg": 260
     },
     "clouds": {
          "all": 20
     },
     "dt": 1779537380,
     "sys": {
          "type": 1,
          "id": 9049,
          "country": "IN",
          "sunrise": 1779495959,
          "sunset": 1779544023
     },
     "timezone": 19800,
     "id": 1279233,
     "name": "Ahmedabad",
     "cod": 200
}

In [24]:
import pandas as pd
df=pd.DataFrame({
    "lon": [final["coord"]["lon"]],
    "lat":[final["coord"]["lat"]],
    "city": [final["name"]],
    "id": [final["id"]]
})
df

       lon      lat       city       id
0  72.5873  23.0258  Ahmedabad  1279233

In [25]:
lat=23.033863
lon=72.585022
key="f29183d2458d620a96494ac639fea754"
url=f"https://api.openweathermap.org/data/2.5/forecast?lat={lat}&lon={lon}&appid={key}"
data=requests.get(url)
data.status_code

200

In [26]:
final=data.json()
new=json.dumps(final,indent=5)
print(new)

{
     "cod": "200",
     "message": 0,
     "cnt": 40,
     "list": [
          {
               "dt": 1779548400,
               "main": {
                    "temp": 311.75,
                    "feels_like": 312.29,
                    "temp_min": 310.9,
                    "temp_max": 311.75,
                    "pressure": 1004,
                    "sea_level": 1004,
                    "grnd_level": 1000,
                    "humidity": 26,
                    "temp_kf": 0.85
               },
               "weather": [
                    {
                         "id": 801,
                         "main": "Clouds",
                         "description": "few clouds",
                         "icon": "02n"
                    }
               ],
               "clouds": {
                    "all": 14
               },
               "wind": {
                    "speed": 3.8,
                    "deg": 296,
                    "gust": 7.21
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "n"
               },
               "dt_txt": "2026-05-23 15:00:00"
          },
          {
               "dt": 1779559200,
               "main": {
                    "temp": 308.97,
                    "feels_like": 310.36,
                    "temp_min": 307.36,
                    "temp_max": 308.97,
                    "pressure": 1006,
                    "sea_level": 1006,
                    "grnd_level": 1001,
                    "humidity": 35,
                    "temp_kf": 1.61
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01n"
                    }
               ],
               "clouds": {
                    "all": 8
               },
               "wind": {
                    "speed": 4.86,
                    "deg": 258,
                    "gust": 8.56
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "n"
               },
               "dt_txt": "2026-05-23 18:00:00"
          },
          {
               "dt": 1779570000,
               "main": {
                    "temp": 304.17,
                    "feels_like": 306.21,
                    "temp_min": 304.17,
                    "temp_max": 304.17,
                    "pressure": 1007,
                    "sea_level": 1007,
                    "grnd_level": 1001,
                    "humidity": 52,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01n"
                    }
               ],
               "clouds": {
                    "all": 3
               },
               "wind": {
                    "speed": 5.86,
                    "deg": 258,
                    "gust": 8.93
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "n"
               },
               "dt_txt": "2026-05-23 21:00:00"
          },
          {
               "dt": 1779580800,
               "main": {
                    "temp": 302.99,
                    "feels_like": 306.27,
                    "temp_min": 302.99,
                    "temp_max": 302.99,
                    "pressure": 1008,
                    "sea_level": 1008,
                    "grnd_level": 1002,
                    "humidity": 63,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01n"
                    }
               ],
               "clouds": {
                    "all": 5
               },
               "wind": {
                    "speed": 4.14,
                    "deg": 259,
                    "gust": 8.19
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "n"
               },
               "dt_txt": "2026-05-24 00:00:00"
          },
          {
               "dt": 1779591600,
               "main": {
                    "temp": 305.16,
                    "feels_like": 308.54,
                    "temp_min": 305.16,
                    "temp_max": 305.16,
                    "pressure": 1010,
                    "sea_level": 1010,
                    "grnd_level": 1005,
                    "humidity": 54,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01d"
                    }
               ],
               "clouds": {
                    "all": 3
               },
               "wind": {
                    "speed": 5.85,
                    "deg": 277,
                    "gust": 7.24
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "d"
               },
               "dt_txt": "2026-05-24 03:00:00"
          },
          {
               "dt": 1779602400,
               "main": {
                    "temp": 310.52,
                    "feels_like": 313.57,
                    "temp_min": 310.52,
                    "temp_max": 310.52,
                    "pressure": 1009,
                    "sea_level": 1009,
                    "grnd_level": 1004,
                    "humidity": 36,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01d"
                    }
               ],
               "clouds": {
                    "all": 2
               },
               "wind": {
                    "speed": 6.06,
                    "deg": 272,
                    "gust": 7.17
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "d"
               },
               "dt_txt": "2026-05-24 06:00:00"
          },
          {
               "dt": 1779613200,
               "main": {
                    "temp": 314.65,
                    "feels_like": 316.83,
                    "temp_min": 314.65,
                    "temp_max": 314.65,
                    "pressure": 1006,
                    "sea_level": 1006,
                    "grnd_level": 1000,
                    "humidity": 25,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01d"
                    }
               ],
               "clouds": {
                    "all": 0
               },
               "wind": {
                    "speed": 6.08,
                    "deg": 275,
                    "gust": 5.49
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "d"
               },
               "dt_txt": "2026-05-24 09:00:00"
          },
          {
               "dt": 1779624000,
               "main": {
                    "temp": 314.24,
                    "feels_like": 315.26,
                    "temp_min": 314.24,
                    "temp_max": 314.24,
                    "pressure": 1004,
                    "sea_level": 1004,
                    "grnd_level": 999,
                    "humidity": 23,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01d"
                    }
               ],
               "clouds": {
                    "all": 0
               },
               "wind": {
                    "speed": 6.51,
                    "deg": 290,
                    "gust": 5.58
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "d"
               },
               "dt_txt": "2026-05-24 12:00:00"
          },
          {
               "dt": 1779634800,
               "main": {
                    "temp": 310.69,
                    "feels_like": 310.37,
                    "temp_min": 310.69,
                    "temp_max": 310.69,
                    "pressure": 1006,
                    "sea_level": 1006,
                    "grnd_level": 1000,
                    "humidity": 25,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01n"
                    }
               ],
               "clouds": {
                    "all": 1
               },
               "wind": {
                    "speed": 3.75,
                    "deg": 272,
                    "gust": 7.09
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "n"
               },
               "dt_txt": "2026-05-24 15:00:00"
          },
          {
               "dt": 1779645600,
               "main": {
                    "temp": 306.72,
                    "feels_like": 306.97,
                    "temp_min": 306.72,
                    "temp_max": 306.72,
                    "pressure": 1007,
                    "sea_level": 1007,
                    "grnd_level": 1002,
                    "humidity": 36,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01n"
                    }
               ],
               "clouds": {
                    "all": 0
               },
               "wind": {
                    "speed": 4.08,
                    "deg": 256,
                    "gust": 7.27
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "n"
               },
               "dt_txt": "2026-05-24 18:00:00"
          },
          {
               "dt": 1779656400,
               "main": {
                    "temp": 303.39,
                    "feels_like": 303.93,
                    "temp_min": 303.39,
                    "temp_max": 303.39,
                    "pressure": 1006,
                    "sea_level": 1006,
                    "grnd_level": 1000,
                    "humidity": 46,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01n"
                    }
               ],
               "clouds": {
                    "all": 0
               },
               "wind": {
                    "speed": 5.81,
                    "deg": 278,
                    "gust": 10.4
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "n"
               },
               "dt_txt": "2026-05-24 21:00:00"
          },
          {
               "dt": 1779667200,
               "main": {
                    "temp": 301.56,
                    "feels_like": 303.62,
                    "temp_min": 301.56,
                    "temp_max": 301.56,
                    "pressure": 1007,
                    "sea_level": 1007,
                    "grnd_level": 1001,
                    "humidity": 63,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01n"
                    }
               ],
               "clouds": {
                    "all": 0
               },
               "wind": {
                    "speed": 5.19,
                    "deg": 283,
                    "gust": 10.35
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "n"
               },
               "dt_txt": "2026-05-25 00:00:00"
          },
          {
               "dt": 1779678000,
               "main": {
                    "temp": 304.42,
                    "feels_like": 306.22,
                    "temp_min": 304.42,
                    "temp_max": 304.42,
                    "pressure": 1009,
                    "sea_level": 1009,
                    "grnd_level": 1003,
                    "humidity": 50,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01d"
                    }
               ],
               "clouds": {
                    "all": 0
               },
               "wind": {
                    "speed": 5.62,
                    "deg": 268,
                    "gust": 7.78
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "d"
               },
               "dt_txt": "2026-05-25 03:00:00"
          },
          {
               "dt": 1779688800,
               "main": {
                    "temp": 311.87,
                    "feels_like": 311.28,
                    "temp_min": 311.87,
                    "temp_max": 311.87,
                    "pressure": 1007,
                    "sea_level": 1007,
                    "grnd_level": 1002,
                    "humidity": 22,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01d"
                    }
               ],
               "clouds": {
                    "all": 0
               },
               "wind": {
                    "speed": 5.41,
                    "deg": 261,
                    "gust": 6.67
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "d"
               },
               "dt_txt": "2026-05-25 06:00:00"
          },
          {
               "dt": 1779699600,
               "main": {
                    "temp": 316.1,
                    "feels_like": 314.46,
                    "temp_min": 316.1,
                    "temp_max": 316.1,
                    "pressure": 1004,
                    "sea_level": 1004,
                    "grnd_level": 998,
                    "humidity": 14,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01d"
                    }
               ],
               "clouds": {
                    "all": 0
               },
               "wind": {
                    "speed": 5.91,
                    "deg": 267,
                    "gust": 6.21
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "d"
               },
               "dt_txt": "2026-05-25 09:00:00"
          },
          {
               "dt": 1779710400,
               "main": {
                    "temp": 314.95,
                    "feels_like": 313.7,
                    "temp_min": 314.95,
                    "temp_max": 314.95,
                    "pressure": 1003,
                    "sea_level": 1003,
                    "grnd_level": 997,
                    "humidity": 16,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01d"
                    }
               ],
               "clouds": {
                    "all": 0
               },
               "wind": {
                    "speed": 7.6,
                    "deg": 280,
                    "gust": 7.13
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "d"
               },
               "dt_txt": "2026-05-25 12:00:00"
          },
          {
               "dt": 1779721200,
               "main": {
                    "temp": 309.72,
                    "feels_like": 308.98,
                    "temp_min": 309.72,
                    "temp_max": 309.72,
                    "pressure": 1005,
                    "sea_level": 1005,
                    "grnd_level": 999,
                    "humidity": 25,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01n"
                    }
               ],
               "clouds": {
                    "all": 0
               },
               "wind": {
                    "speed": 6.57,
                    "deg": 274,
                    "gust": 10.25
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "n"
               },
               "dt_txt": "2026-05-25 15:00:00"
          },
          {
               "dt": 1779732000,
               "main": {
                    "temp": 305.44,
                    "feels_like": 306.04,
                    "temp_min": 305.44,
                    "temp_max": 305.44,
                    "pressure": 1006,
                    "sea_level": 1006,
                    "grnd_level": 1000,
                    "humidity": 41,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01n"
                    }
               ],
               "clouds": {
                    "all": 0
               },
               "wind": {
                    "speed": 4.29,
                    "deg": 248,
                    "gust": 7.65
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "n"
               },
               "dt_txt": "2026-05-25 18:00:00"
          },
          {
               "dt": 1779742800,
               "main": {

In [27]:
date=[]
time=[]
temp_k=[]
temp_d=[]
temp_f=[]
for i in final["list"]:
    d=i["dt_txt"]
    date.append(d.split(" ")[0])
    time.append(d.split(" ")[1])
    temp_k.append(i["main"]["temp"])
    temp_d.append((i["main"]["temp"]-273.15))
    temp_f.append((i["main"]["temp"])*(9/5)+32)

In [28]:
data={"date":date,
      "time":time,
      "temp_k":temp_k,
      "temp_d":temp_d,
      "temp_f":temp_f
     }
df=pd.DataFrame(data)
df

          date      time  temp_k  temp_d   temp_f
0   2026-05-23  15:00:00  311.75   38.60  593.150
1   2026-05-23  18:00:00  308.97   35.82  588.146
2   2026-05-23  21:00:00  304.17   31.02  579.506
3   2026-05-24  00:00:00  302.99   29.84  577.382
4   2026-05-24  03:00:00  305.16   32.01  581.288
5   2026-05-24  06:00:00  310.52   37.37  590.936
6   2026-05-24  09:00:00  314.65   41.50  598.370
7   2026-05-24  12:00:00  314.24   41.09  597.632
8   2026-05-24  15:00:00  310.69   37.54  591.242
9   2026-05-24  18:00:00  306.72   33.57  584.096
10  2026-05-24  21:00:00  303.39   30.24  578.102
11  2026-05-25  00:00:00  301.56   28.41  574.808
12  2026-05-25  03:00:00  304.42   31.27  579.956
13  2026-05-25  06:00:00  311.87   38.72  593.366
14  2026-05-25  09:00:00  316.10   42.95  600.980
15  2026-05-25  12:00:00  314.95   41.80  598.910
16  2026-05-25  15:00:00  309.72   36.57  589.496
17  2026-05-25  18:00:00  305.44   32.29  581.792
18  2026-05-25  21:00:00  302.79   29.64  577.022
19  2026-05-26  00:00:00  301.51   28.36  574.718
20  2026-05-26  03:00:00  304.65   31.50  580.370
21  2026-05-26  06:00:00  311.62   38.47  592.916
22  2026-05-26  09:00:00  315.67   42.52  600.206
23  2026-05-26  12:00:00  314.21   41.06  597.578
24  2026-05-26  15:00:00  309.14   35.99  588.452
25  2026-05-26  18:00:00  305.17   32.02  581.306
26  2026-05-26  21:00:00  302.86   29.71  577.148
27  2026-05-27  00:00:00  301.79   28.64  575.222
28  2026-05-27  03:00:00  304.32   31.17  579.776
29  2026-05-27  06:00:00  311.65   38.50  592.970
30  2026-05-27  09:00:00  316.21   43.06  601.178
31  2026-05-27  12:00:00  316.63   43.48  601.934
32  2026-05-27  15:00:00  307.00   33.85  584.600
33  2026-05-27  18:00:00  304.38   31.23  579.884
34  2026-05-27  21:00:00  303.44   30.29  578.192
35  2026-05-28  00:00:00  302.24   29.09  576.032
36  2026-05-28  03:00:00  304.96   31.81  580.928
37  2026-05-28  06:00:00  312.04   38.89  593.672
38  2026-05-28  09:00:00  316.80   43.65  602.240
39  2026-05-28  12:00:00  316.43   43.28  601.574

In [1]:
import matplotlib.pyplot as plt
plt.bar([1,2,3,4,5],df[df["time"]=="12:00:00"]["temp_d"])

NameError: name 'df' is not defined